language: node_js
node_js: 
  - 14.5.0
cache: yarn
install:
  - yarn install
script:
  - yarn test
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on: 
    branch: master